### PR TITLE
feat: unify android share extension into one single plugin

### PR DESCRIPTION
**Pull request by achorein**
Simplify android integration with one single plugin for android. This build is for Expo 49 (gradle 1.8 with updated react-native-receive-sharing-intent patch)

**TODO**

- [x] Handle gradle build properties (kotlin 1.6) and remove `expo-build-properties` dependency
- [x] Handle manifest main activity attributes (singleTask mode)
- [x] Handle android share intent action auto configuration (expo / android / shareIntent)
- [x] Remove manual patching after prebuild (https://github.com/achorein/expo-share-intent-demo/pull/6)
- [x] Update README.md

**TEST**

- [x] Node 16
- [x] Android Studio Flamingo (2022.2.1 Patch2) / Pixel 4XL simulator
- [x] EAS Build and real device test

### CODE REVIEW

**Comment by achorein** [comment]
You should take a look @Randall71 @kayode0x

**Comment by Randall71** [comment]
Right now, EAS Build reject on app config evaluation, one or more thing don't work properly with the config 

`Failed to resolve plugin for module "./plugins/withAndroidShareExtension"`

**Comment by achorein** [comment]
eas build fixed, 
but got the share intent detected only in simulator not on real device ("developmentClient"), maybe a android studio difference on eas build.

**Comment by achorein** [comment]
i tested the plugin for sdk 46 to 48 with success and update corresponding branches. still have a problem with 49.

**Comment by Randall71** [comment]
I created three organizations on Expo to facilitate testing on SDK **46**, **47**, and **48**, and to avoid running into the concurrent build limit (I hope Expo will understand 😅).

### Android
- [x]  SDK 46
- [x] SDK 47
- [x]  SDK 48

### IOS
- [x]  SDK 46
- [x] SDK 47
- [x]  SDK 48

Regarding SDK 48 on Android, there was an issue with image sharing. However, after removing the duplicate line in the app.json file, everything is functioning correctly on real device 🔥.

Now, only SDK 49 remains to be addressed 🙌.

**Comment by Randall71** [comment]
I created three organizations on Expo to facilitate testing on SDK 46, 47, and 48, and to avoid running into the concurrent build limit (I hope Expo will understand 😅).

### Android
- [X]  SDK 46
- [X]  SDK 47
- [X]  SDK 48

### IOS
- [X]  SDK 46
- [X]  SDK 47
- [X]  SDK 48

Regarding SDK 48 on Android, there was an issue with image sharing. However, after removing the duplicate line in the app.json file, everything is functioning correctly on real device 🔥.

Now, only SDK 49 remains to be addressed 🙌.

**Comment by kayode0x** [comment]
Awesome work y'all! Expo 49 had issues when I upgraded, lot were for external dependencies.

**Comment by Randall71** [comment]
@achorein Just tested it with SDK 49 and it work well on Android and IOS on my side

**Comment by achorein** [comment]
thank you for the test, i think is globally a random dependency tree problem, but not related to the plugin (package `react-native-receive-sharing-intent` should be upgrade to gradle 8 or migrate the code to a expo native module...).

**Pull request merged**
